spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    #url: jdbc:sqlserver://localhost:1433;databaseName=FinalProject;trustServerCertificate=true


    #url: jdbc:sqlserver://192.168.34.5:1433;databaseName=FinalProject;trustServerCertificate=true

    
    username: sa

    password: P@ssw0rd



    url: jdbc:sqlserver://localhost:1433;databaseName=FinalProject;trustServerCertificate=true


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true    
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

     
